sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ytytyt86

  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: 12345678
    bucket: sky-take-out
